## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('applications', ['internet', 'config-store','stats'])
    module.source = [
        'model/bulk-send-application.cc',
        'model/onoff-application.cc',
        'model/packet-sink.cc',
        'model/udp-client.cc',
        'model/udp-server.cc',
        'model/seq-ts-header.cc',
        'model/udp-trace-client.cc',
        'model/packet-loss-counter.cc',
        'model/udp-echo-client.cc',
        'model/udp-echo-server.cc',
        'model/application-packet-probe.cc',
        'model/three-gpp-http-client.cc',
        'model/three-gpp-http-server.cc',
        'model/three-gpp-http-header.cc',
        'model/three-gpp-http-variables.cc', 
        'helper/bulk-send-helper.cc',
        'helper/on-off-helper.cc',
        'helper/packet-sink-helper.cc',
        'helper/udp-client-server-helper.cc',
        'helper/udp-echo-helper.cc',
        'helper/three-gpp-http-helper.cc',
	'model/bitcoin.cc',
	'model/bitcoin-node.cc',
	'model/bitcoin-miner.cc',
	'model/consens-node.cc',
	'model/bitcoin-simple-attacker.cc',
	'model/bitcoin-selfish-miner.cc',
	'model/bitcoin-selfish-miner-trials.cc',
	'helper/bitcoin-topology-helper.cc',
	'helper/bitcoin-node-helper.cc',
	'helper/bitcoin-miner-helper.cc',
	'helper/consens-node-helper.cc',
	]

    applications_test = bld.create_ns3_module_test_library('applications')
    applications_test.source = [
        'test/three-gpp-http-client-server-test.cc', 
        'test/udp-client-server-test.cc'
        ]

    headers = bld(features='ns3header')
    headers.module = 'applications'
    headers.source = [
        'model/bulk-send-application.h',
        'model/onoff-application.h',
        'model/packet-sink.h',
        'model/udp-client.h',
        'model/udp-server.h',
        'model/seq-ts-header.h',
        'model/udp-trace-client.h',
        'model/packet-loss-counter.h',
        'model/udp-echo-client.h',
        'model/udp-echo-server.h',
        'model/application-packet-probe.h',
        'model/three-gpp-http-client.h',
        'model/three-gpp-http-server.h',
        'model/three-gpp-http-header.h',
        'model/three-gpp-http-variables.h',
        'helper/bulk-send-helper.h',
        'helper/on-off-helper.h',
        'helper/packet-sink-helper.h',
        'helper/udp-client-server-helper.h',
        'helper/udp-echo-helper.h',
        'helper/three-gpp-http-helper.h',
	'model/bitcoin.h',
	'model/bitcoin-node.h',
	'model/bitcoin-miner.h',
	'model/consens-node.h',
	'model/bitcoin-simple-attacker.h',
	'model/bitcoin-selfish-miner.h',
	'model/bitcoin-selfish-miner-trials.h',
	'helper/bitcoin-topology-helper.h',
	'helper/bitcoin-node-helper.h',
	'helper/bitcoin-miner-helper.h',
	'helper/consens-node-helper.h',
	]
    
    if (bld.env['ENABLE_EXAMPLES']):
        bld.recurse('examples')

    bld.ns3_python_bindings()
